name: GAXE
main: GAXE\Main
version: 1.0.0
api: 5.0.0
author: ZyberPE

commands:
  gaxe:
    description: Get your custom axe
    usage: /gaxe
    permission: gaxe.use

permissions:
  gaxe.use:
    default: op
