# Messages
messages:
  received: "&aYou received your GAXE!"
  no-permission: "&cYou do not have permission!"
  cooldown: "&eWait {time} seconds before using this again."

# Cooldown in seconds
cooldown: 60

# Axe Settings
axe:
  name: "&b&lGOD AXE"
  lore:
    - "&7This is a powerful axe"
    - "&eUse it wisely!"
  show-enchants-in-lore: true

  enchants:
    - "efficiency:5"
    - "unbreaking:3"
